package com.mtech.travces.utils.extensions

import java.io.Serializable

const val ERROR_CODE_EMPTY_REGISTRATION_NO_FIELD = -10
const val ERROR_CODE_EMPTY_CATEGORY_FIELD = -11
const val ERROR_CODE_EMPTY_VEHICLE_COMPANY_NAME_FIELD = -12
const val ERROR_CODE_EMPTY_VEHICLE_NAME_FIELD = -13
const val ERROR_CODE_EMPTY_COLOR_FIELD = -14
const val ERROR_CODE_EMPTY_REGISTRATION_YEAR_FIELD = -15
const val ERROR_CODE_INVALID_REGISTRATION_NO_FIELD = -16
const val ERROR_CODE_EMPTY_CONFIRM_PIN_CODE_FIELD = -17
const val ERROR_CODE_EMPTY_PIN_CODE_FIELD = -18
const val ERROR_CODE_EMPTY_CNIC_NUMBER_FIELD = -19
const val ERROR_CODE_EMPTY_EMAIL_FIELD = -20
const val ERROR_CODE_EMPTY_NAME_FIELD = -21
const val ERROR_CODE_PLEASE_UPLOAD_ALL_IMAGES = -22
const val ERROR_CODE_INVALID_EMAIL = -23
const val ERROR_CODE_PIN_CODE_MISMATCH = -24
const val ERROR_CODE_INVALID_PIN_CODE = -25
const val ERROR_CODE_INVALID_CNIC = -26
const val ERROR_CODE_CITY_NOT_SELECTED = -27
const val ERROR_CODE_INVALID_NAME = -28
const val ERROR_CODE_ACCEPT_TERM_AND_CONDITIONS = -29
const val ERROR_CODE_EMPTY_FIRST_NAME_FIELD = -30
const val ERROR_CODE_EMPTY_LAST_NAME_FIELD = -31
const val ERROR_CODE_EMPTY_PHONE_FIELD = -32
const val ERROR_CODE_INVALID_PHONE_FIELD = -33
const val ERROR_CODE_EMPTY_ZIP_CODE_FIELD = -34
const val ERROR_CODE_EMPTY_AGE_FIELD = -35
const val ERROR_CODE_EMPTY_IMAGE_PATH = -36
const val ERROR_CODE_EMPTY_OLD_PASSWORD = -37
const val ERROR_CODE_EMPTY_PASSWORD = -38
const val ERROR_CODE_EMPTY_CONFIRM_PASSWORD = -39
const val ERROR_CODE_INVALID_OLD_PASSWORD = -40
const val ERROR_CODE_INVALID_NEW_PASSWORD = -41
const val ERROR_CODE_INVALID_CONFIRM_PASSWORD = -42
const val ERROR_CODE_SOCIAL_LOGIN_FAILED = -43
const val ERROR_CODE_EMPTY_NOTE_TITLE = -53
const val ERROR_CODE_EMPTY_NOTE_DESCRIPTION = -54
const val ERROR_CODE_EMPTY_ADDRESS = -89
const val ERROR_CODE_EMPTY_CNIC = -90
const val ERROR_CODE_INVALID_PHONE = -99
const val ERROR_CODE_PICKUP_LOCATION_NAME = -109
const val ERROR_CODE_DROP_LOCATION_NAME = -110

const val ERROR_CODE_WRONG_NUMBER_FORMAT = -12


class ErrorResponse(var errorMessage: String, var errorCode: Int) : Serializable